# Most content of .zshrc will be auto-generated by oh-my-zsh.sh and installed tools like zoxide, bun, ...
# But here a few custom things I did setup for myself:

# Path to my own bash-scripts to be able to run them directly
export PATH=$PATH:/Users/tobiaskraus/dev/bash-scripts

# --menu=false cause with its interactive mode I cannot send process to background (^+Z)
alias dcu="docker compose up --menu=false"

alias dcd="docker compose down"

alias lg="lazygit"
